SimpletourDevops/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from webapp.views import index
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^web/', include('webapp.urls')),
    url(r'^docker/',include('dockermanager.urls')),
    url(r'^server/',include('servermanager.urls')),
   # url(r'^domain/', include('domainmanager.urls')),
    url(r'^salt/',include('saltadmin.urls')),
]

saltadmin/urls.py
from django.conf.urls import url

from saltadmin.views import (KeyList,Minion_Status,SoftInstall,JobList,RemoteCmd,SaltMasterList,
                              SaltMinionGrains,CmdResult,jobdetail,DeployResult,SaltMasterDelete,
                              SalMasterChange
                             )

urlpatterns = [
    url(r'keylist/', KeyList, name='KeyList'),
    url(r'minion/status/',Minion_Status,name='Minion_Status'),
    url(r'minion/softinstall/',SoftInstall,name='SoftInstall'),
    url(r'job/list/(?P<page>\d+)',JobList,name='JobList'),
    url(r'cmd/$',RemoteCmd,name='RemoteCmd'),
    url(r'master/$',SaltMasterList,name='SaltMasterList'),
    url(r'master/delete/(?P<masterid>\d+)$',SaltMasterDelete,name='SaltMasterDelete'),
    url(r'master/change/(?P<masterid>\d+)$',SalMasterChange,name='SalMasterChange'),
    url(r'grains/$',SaltMinionGrains,name='SaltMinionGrains'),
    url(r'cmdresult/(?P<jid>\d+)$',CmdResult,name='CmdResult'),
    url(r'deployresult/(?P<jid>\d+)$',DeployResult,name='DeployResult'),
    url(r'job/detail/$',jobdetail,name='jobdetail'),
]

webapp/urls.py
from django.conf.urls import url
from webapp.views import (Login,
                          Logout,
                          Register,
                          Activate,
                          SendResetEmail,
                          ResetPassword,
                          SysrestUserpassword,
                          Userinfo)

urlpatterns = [
    url(r'login/$', Login, name='Login'),
    url(r'register/$', Register, name='Register'),
    url(r'logout/$', Logout, name='Logout'),
    url(r'activate/(?P<token>\w+@\w+.\w+.[-_\w]*\w+.[-_\w]*\w+)/$', Activate, name='Activate'),
    url(r'reset/$',SendResetEmail,name='SendResetEmail'),
    url(r'resetpass/(?P<token>\w+@\w+.\w+.[-_\w]*\w+.[-_\w]*\w+)/$', ResetPassword, name='ResetPassword'),
    url(r'userinfo/$',Userinfo, name='Userinfo'),
    url(r'restuserpass/(\d+)$', SysrestUserpassword, name='SysrestUserpassword'),

]

saltadmin/models.py
#coding:utf8
from __future__ import unicode_literals

from django.db import models

class SaltServer(models.Model):
    Role = (
    ('Master', 'Master'),
    ('Backend', 'Backend'),
    )
    url = models.URLField(max_length=100,verbose_name=u'URL地址')
    username = models.CharField(max_length=50, verbose_name=u'用户名')
    password = models.CharField(max_length=50,verbose_name=u'密码')
    role = models.CharField(choices=Role,max_length=20,default='Master',verbose_name=u'角色')

    def __unicode__(self):
        return u"%s - %s" %(self.url,self.role)

    class Meta:
        verbose_name = u'Salt服务器'
        verbose_name_plural = u'Salt服务器列表'
        permissions = (
            ("salt_index_view", "Can view %s"  % verbose_name),
        )


class Modules(models.Model):
    name = models.CharField(max_length=20,verbose_name=u'Salt模块名称')
    models_site = models.CharField(max_length=50,null=True,blank=True,verbose_name=u'Salt模块参数')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Salt软件'
        verbose_name_plural = u'Salt软件'


'''
class Command(models.Model):
    cmd = models.CharField(max_length=100,verbose_name=u'Salt命令')
    doc = models.TextField(max_length=2000,blank=True,verbose_name=u'帮助文档')
    module = models.ForeignKey(Module,verbose_name=u'所属模块')

    def __unicode__(self):
        return  u"%s - %s"%(self.module,self.cmd)

    class Meta:
        verbose_name = u'Salt命令'
        verbose_name_plural = u'Salt命令列表'
        unique_together = ("module", "cmd")
'''

class Minions(models.Model):
    Status = (
    ('Accepted', 'Accepted'),
    ('Unaccepted', 'Unaccepted'),
    ('Rejected', 'Rejected'),
    )
    minion = models.CharField(max_length=50,verbose_name=u'客户端',unique=True)
    saltserver = models.ForeignKey(SaltServer,verbose_name=u'所属Salt服务器')
    status = models.CharField(choices=Status,max_length=20,default='Unknown',verbose_name=u'Key状态')
    create_date=models.DateTimeField(auto_now_add=True,verbose_name=u'创建时间')

    def __unicode__(self):
        return self.minion

    class Meta:
        verbose_name = u'Salt客户端'
        verbose_name_plural = u'Salt客户端列表'


class MinionStatus(models.Model):
    minion = models.OneToOneField(Minions)
    minion_status = models.CharField(max_length=20,verbose_name=u'在线状态')
    # 上次检测时间
    alive_time_last = models.DateTimeField(auto_now=True,null=True)
    # 当前检测时间
    alive_time_now = models.DateTimeField(auto_now=True,null=True)

class MinionGroup(models.Model):
    groupname = models.CharField(u'Minion组',max_length=50,default='default')
    minions = models.ManyToManyField(Minions,verbose_name=u'Minions',blank=True)

    def __unicode__(self):
        return self.groupname

    class Meta:
        verbose_name = u'Minion组'
        verbose_name_plural = u'Minion组'


class CmdRunLog(models.Model):
    user=models.CharField(max_length=30)
    time=models.DateTimeField(auto_now_add=True,null=True)
    target=models.CharField(max_length=500)
    cmd=models.CharField(max_length=500)
    total=models.IntegerField()
    runsuccess = models.IntegerField(default=0)
    runerror = models.IntegerField(default=0)
    runresult = models.TextField(max_length=65535,null=True,blank=True)

    class Meta:
        verbose_name = u'命令执行日志'
        verbose_name_plural = u'命令执行日志'


class SaltJobs(models.Model):
    jid = models.CharField(max_length=50,unique=True)
    args = models.CharField(max_length=50,null=True,blank=True)
    function = models.CharField(max_length=50)
    startTime = models.CharField(max_length=100)
    target = models.CharField(max_length=500)
    user = models.CharField(max_length=50)
    saltserver = models.CharField(max_length=100,null=True,blank=True)

    class Meta:
        verbose_name = u'Jobs列表'
        verbose_name_plural = u'Jobs列表'



class ModuleDeployLog(models.Model):
    user=models.CharField(max_length=50)
    time=models.DateTimeField()
    target=models.CharField(max_length=100)
    application=models.CharField(max_length=100)
    #成功的主机
    success_hosts=models.CharField(max_length=500)
    #失败的主机
    failed_hosts=models.CharField(max_length=500)
    #执行总共结果
    total=models.IntegerField()
    #执行过程
    log=models.TextField()
    #持续时间
    duration=models.CharField(max_length=500)
    class Meta:
        verbose_name = u'软件部署'
        verbose_name_plural = u'软件部署'

saltadmin/views.py
#coding:utf8
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from saltadmin.models import *
from Publicapi.saltstackapi.SaltConApi import SaltApi
import json
from django.db.models import Q
from saltadmin.forms import CheckSaltServer,KeyManager
from webapp.Extends import PageList
import yaml
from saltadmin.Minions_Controller import JobResultFromat
from webapp.models import Operation




@login_required()
def SaltMasterList(request):
    usersession = request.session.get('user_id')
    form = CheckSaltServer()
    if request.method == 'POST':
        form = CheckSaltServer(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/salt/master/')
        else:
            form = form
    SaltMasterData = SaltServer.objects.all()
    Role=SaltServer.Role
    return render(request, 'saltadmin/saltmaster_list.html', locals())


@login_required()
def SaltMasterDelete(request,masterid):
    user_name = request.session.get('user_name')
    if request.method == 'GET':
        SaltServer.objects.get(id=masterid).delete()
        Operation.objects.create(Opuser=user_name, Opaction=u'删除salt主机')
        msg = {'msginfo': u'Salt主机及所有管理信息已经删除成功!!'}
        return HttpResponse(json.dumps(msg))


@login_required()
def SalMasterChange(request,masterid):
    user_name = request.session.get('user_name')
    if request.method == 'POST':
        url = request.POST.get('url')
        username  = request.POST.get('username')
        password = request.POST.get('password')
        role = request.POST.get('role')

        Changeserver = SaltServer.objects.get(id=masterid)
        Changeserver.url = url
        Changeserver.username = username
        Changeserver.password = password
        Changeserver.role = role
        Changeserver.save()
        Operation.objects.create(Opuser=user_name, Opaction=u'修改salt主机信息')
        msg = {'msginfo': u'Master修改成功!!!!',}
        return HttpResponse(json.dumps(msg))

    else:
        Changeserver = SaltServer.objects.get(id=masterid)
        data = {'url': Changeserver.url,'username':Changeserver.username,'password':Changeserver.password,'role':Changeserver.role }
        return HttpResponse(json.dumps(data))








@login_required()
def KeyList(request):
    usersession = request.session.get('user_id')
    user_name = request.session.get('user_name')
    if request.method == 'GET':
        Accepted = Minions.objects.filter(status='Accepted')
        Unaccepted = Minions.objects.filter(status='Unaccepted')
        Rejected = Minions.objects.filter(status='Rejected')
        froms=KeyManager()
        return render(request,'saltadmin/key_list.html',locals())


    if request.method == 'POST':
        minion = request.POST.get('minion')
        status = request.POST.get('status')
        Minion_data=Minions.objects.get(minion=minion)
        Minion_data.status = status
        Minion_data.save()
        Operation.objects.create(Opuser=user_name, Opaction=u'修改 minion Key状态 %s to %s' %(Minion_data.minion,status))
        url = Minion_data.saltserver.url

        username = Minion_data.saltserver.username
        password = Minion_data.saltserver.password

        salt = SaltApi(url, username, password)
        if status == 'Accepted':
            ret = salt.AcceptKey(minion)
        elif status == 'Unaccepted':
            ret = salt.DeleteKey(minion)
        elif status == 'Rejected':
            ret = salt.RejectKey(minion)

        return HttpResponse('OK')






@login_required()
def Minion_Status(request):
    usersession = request.session.get('user_id')
    if request.method == 'GET':
        SaltMinionData = MinionStatus.objects.filter(minion__status='Accepted')
        return render(request,'saltadmin/minion_status.html',locals())








@login_required()
def SoftInstall(request):
    usersession = request.session.get('user_id')
    user_name = request.session.get('user_name')
    if request.method == 'GET':
        SoftModuleData = Modules.objects.all()
        GroupData = MinionGroup.objects.all()
        # hosts = """[ {type: 1, list: [{ text: 'yang', id: 1}, {text: 'asdasd',id: 4}]}, }]"""

        groupall = []
        for g in GroupData:
            group = {}
            list = []
            for m in g.minions.all():
                dir = {}
                dir['text'] = m.minion
                dir['id'] = m.minion
                list.append(dir)

            group['type'] = g.id
            group['list'] = list
            groupall.append(group)
        groupall = json.dumps(groupall)

        return render(request,'saltadmin/saltmodule_deploy.html',locals())

    else:
        if not request.POST.get('minion'):
            minions_id = request.POST.get('minion_group')
            minions_data=MinionGroup.objects.get(id=minions_id).minions.all()
        else:
            minions_data = request.POST.getlist('minion')

        minions_list = ''
        for m in minions_data:
            minions_list += str(m) + ','
        minions_list = minions_list.strip(',')

        software = request.POST.getlist('software')
        salt_env = request.POST.get('env')

        soft=''
        for i in software:
            soft += i + ','
        soft=soft.strip(',')


        saltm = Minions.objects.get(minion=minions_list.split(',')[0])

        url = saltm.saltserver.url
        username = saltm.saltserver.username
        password = saltm.saltserver.password

        salt = SaltApi(url, username, password)

        jid = salt.Softwarete_deploy(minions_list,arg=["saltenv=%s" %(salt_env), str(soft), 'test=True'])

        Operation.objects.create(Opuser=user_name, Opaction=u'部署软件 %s' %soft)
        #savelog = CmdRunLog.objects.create(user=user_name, target=minions_list, cmd=cmd, total=len(minions_list.split(',')))

        ret={'jid':jid,'minion':minions_list,'savelogid':1}
        return  HttpResponse(json.dumps(ret))






@login_required()
def JobList(request,page):
    usersession = request.session.get('user_id')
    if request.method == 'GET':

        # 分页代码
        (page, start, end, per_item) = PageList.PageCount(page)
        count = SaltJobs.objects.filter(~Q(function='test.ping')).count()
        result = SaltJobs.objects.filter(~Q(function='test.ping')).order_by('-jid')[start:end]
        url = "/salt/job/list"
        if count % per_item == 0:
            all_pages_count = count / per_item
        else:
            all_pages_count = count / per_item + 1
        page = PageList.Page(page, url, all_pages_count)
        ret = {'SaltMaster_data': result,
               'count': count,
               'page': page,
               'usersession': usersession}

        return render(request,'saltadmin/saltjob_list.html',ret)


@login_required()
def jobdetail(request):
    if request.method == 'GET':
        jid = request.GET.get('jid')
        print jid
        jiddata = SaltJobs.objects.get(jid=jid)
        masterdata = SaltServer.objects.get(url=jiddata.saltserver)
        url = masterdata.url
        username =masterdata.username
        password = masterdata.password

        salt = SaltApi(url, username, password)
        resultdata = salt.salt_runner(jid)
        return HttpResponse(json.dumps(resultdata))





@login_required()
def RemoteCmd(request):
    usersession = request.session.get('user_id')
    user_name = request.session.get('user_name')

    if request.method == 'GET':
        GroupData = MinionGroup.objects.all()
        #hosts = """[ {type: 1, list: [{ text: 'yang', id: 1}, {text: 'asdasd',id: 4}]}, }]"""

        groupall=[]
        for g in GroupData:
            group={}
            list = []
            for m in g.minions.all():
                dir = {}
                dir['text']  = m.minion
                dir['id'] = m.minion
                list.append(dir)

            group['type'] = g.id
            group['list'] = list
            groupall.append(group)
        groupall=json.dumps(groupall)
        return render(request,'saltadmin/salt_cmd.html',locals())

    else:
        if not request.POST.get('minion'):
            minions_id = request.POST.get('minion_group')
            minions_data=MinionGroup.objects.get(id=minions_id).minions.all()

        else:
            minions_data = request.POST.getlist('minion')

        minions_list = ''
        for m in minions_data:
            minions_list += str(m) + ','
        minions_list = minions_list.strip(',')


        cmd =request.POST.get('cmd')
        #必须是同一台master上的才能为一个组，这样只需要查询一个就可

        saltm = Minions.objects.get(minion=minions_list.split(',')[0])
        url = saltm.saltserver.url
        username = saltm.saltserver.username
        password = saltm.saltserver.password

        salt = SaltApi(url, username, password)
        jid = salt.shell_remote_execution(minions_list, cmd)
        Operation.objects.create(Opuser=user_name, Opaction=u'执行命令 %s' %cmd)

        savelog = CmdRunLog.objects.create(user=user_name, target=minions_list, cmd=cmd, total=len(minions_list.split(',')))


        ret={'jid':jid,'minion':minions_list,'savelogid':savelog.id}
        return  HttpResponse(json.dumps(ret))





@login_required()
def CmdResult(request,jid):
    if request.method == 'GET':
        minions_list = request.GET.get('minion')
        savelogid = request.GET.get('savelogid')

        saltm = Minions.objects.get(minion=minions_list.split(',')[0])
        url = saltm.saltserver.url
        username = saltm.saltserver.username
        password = saltm.saltserver.password

        salt = SaltApi(url,username,password)
        resultdata = salt.salt_runner(jid)

        print savelogid
        logs = CmdRunLog.objects.get(id=savelogid)
        logs.runresult=resultdata
        logs.runsuccess=len(resultdata)
        logs.save()

templates/saltadmin/key_list.html
{% extends 'base.html' %}


{% block content %}


<div class="container">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <h4 class="page-title">SALT 管理</h4>
                <ol class="breadcrumb">
                    <li>
                        <a href="{% url 'SaltMasterList' %}">SaltStack Master管理</a>
                    </li>

                    <li class="active">
                        SaltStack Master列表
                    </li>
                </ol>
            </div>
        </div>

        <div class="row">
             <div class="col-sm-10">
                   <div class="card-box">

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel-group" id="accordion-test-2">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseOne-2" aria-expanded="true" class="">
                                                    已经接受的Key <span class="badge badge-warning" style="margin-top: 0;background-color: #ffbd4a;">{{Accepted.count}}</span>
                                                </a>
                                            </h4>
                                        </div>

                                        <div id="collapseOne-2" class="panel-collapse collapse in" >
                                            <div class="panel-body">
                                                <table class="table">
													<thead>
														<tr>

															<th>Minion</th>
															<th>saltserver</th>
															<th>状态</th>
                                                            <th>操作</th>
														</tr>
													</thead>
													<tbody>
                                                        {% for a in Accepted%}
														<tr>

															<td>{{a.minion}}</td>
															<td>{{a.saltserver}}</td>
															<td>{{a.status}}</td>
                                                            <td>

                                                                <button  class="btn btn-xs btn-info" onclick="Update('{{a.minion}}')" data-toggle="modal" data-target="#myModal">修改</button>

                                                            </td>
														</tr>
                                                        {%endfor%}
													</tbody>
												</table>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseTwo-2" class="collapsed" aria-expanded="false">
                                                    未接受的Key <span class="badge badge-warning" style="margin-top: 0;background-color: #34d3eb;">{{Unaccepted.count}}</span>
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="collapseTwo-2" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                            <div class="panel-body">
                                                 <table class="table">
													<thead>
														<tr>

															<th>Minion</th>
															<th>saltserver</th>
															<th>状态</th>
                                                            <th>操作</th>
														</tr>
													</thead>
													<tbody>
                                                        {% for a in Unaccepted%}
														<tr>

															<td>{{a.minion}}</td>
															<td>{{a.saltserver}}</td>
															<td>{{a.status}}</td>
                                                            <td>
                                                                <button  class="btn btn-xs btn-info" onclick="Update('{{a.minion}}')" data-toggle="modal" data-target="#myModal">修改</button>

                                                            </td>
														</tr>
                                                        {%endfor%}
													</tbody>
												</table>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseFive-2" aria-expanded="false" class="collapsed" >
                                                   已拒绝的Key <span class="badge badge-danger" style="margin-top: 0;background-color: #f05050;">{{Rejected.count}}</span>
                                                </a>
                                            </h4>
                                        </div>

                                        <div id="collapseFive-2" class="panel-collapse collapse" >
                                            <div class="panel-body">
                                                <table class="table">
													<thead>
														<tr>

															<th>Minion</th>
															<th>saltserver</th>
															<th>状态</th>
                                                            <th>操作</th>
														</tr>
													</thead>
													<tbody>
                                                        {% for a in Rejected%}
														<tr>

															<td>{{a.minion}}</td>
															<td>{{a.saltserver}}</td>
															<td>{{a.status}}</td>
                                                            <td>
                                                                <button  class="btn btn-xs btn-info" onclick="Update('{{a.minion}}')" data-toggle="modal" data-target="#myModal">修改</button>

                                                            </td>
														</tr>
                                                        {%endfor%}

													</tbody>
												</table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                       <div id="myModal" class="modal fade " tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none; padding-right: 17px;">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h4 class="modal-title" id="myModalLabel">Key状态修改</h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label for="field-1"  id="status" class="control-label">状态</label>
                                            {{froms.status}}
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">取消</button>
                                        <button type="button" class="btn btn-primary waves-effect waves-light" onclick="keyChange()">确认修改</button>
                                    </div>
                                </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                        </div>

                   </div>
              </div>
        </div>
   <script src="/static/assets/plugins/custombox/dist/custombox.min.js"></script>
    <script src="/static/assets/plugins/custombox/dist/legacy.min.js"></script>
    <script>
        function Update(minion) {
            var Selectminion =document.getElementById("myModal");
            Selectminion.setAttribute('data-minion',minion);
        };

        function keyChange(){
            var nowStatus = $('#id_status').val();
            var Selectminion =document.getElementById("myModal");
            $.ajax({
                method: 'post',
                url:'{% url 'KeyList' %}',
                datatype: 'json',
                data:{
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    status: nowStatus,
                    minion: Selectminion.getAttribute('data-minion'),
                },
                success: function (data) {
                    if(data == 'OK'){
                        $('#myModal').modal('hide');
                        location.href = '{% url 'KeyList' %}';
                    }
                },
                error: function () {

                }
            });
        }

    </script>



{% endblock %}

templates/saltadmin/minion_status.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <h4 class="page-title">SALT 管理</h4>
                <ol class="breadcrumb">
                    <li>
                        <a href="{% url 'SaltMasterList' %}">Minion 状态管理</a>
                    </li>
                    <li class="active">
                        SaltStack Minion Status 列表
                    </li>
                </ol>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-10">

                <div class="card-box">

                    <div class="row">
                        <div class="col-sm-12">
                            <h4 class="m-t-0 header-title"><b>Minion 列表</b></h4>
                            <div class="p-20">
                                <table class="table table-striped m-0">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Minion</th>
                                            <th>saltmaster</th>
                                            <th>UP/Offline</th>
                                            <th>grains信息</th>
                                            <th>pillar信息</th>

                                        </tr>
                                    </thead>

                                    <tbody>
                                        {% for minion in SaltMinionData%}
                                        <tr>
                                            <th scope="row" data-id="{{minion.id}}">{{minion.id}}</th>
                                            <td>{{minion.minion}}</td>
                                            <td>{{minion.minion.saltserver}}</td>
                                            <td>{{minion.minion_status}}</td>
                                            <td><button class="btn btn-xs btn-info" data-toggle="modal" data-target=".bs-example-modal-lg" onclick="GetGrainsPillar({{minion.id}},'grains')" >view</button></td>
                                            <td><button class="btn btn-xs btn-info" data-toggle="modal" data-target=".bs-example-modal-lg" onclick="GetGrainsPillar({{minion.id}},'pillar')" >view</button></td>

                                        </tr>
                                        {% endfor%}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>


<div class="modal fade bs-example-modal-lg" id="grains" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" >Grains信息</h4>
            </div>

                <div class="modal-body">
                    <textarea style="OVERFLOW-Y: auto; color:#A6FFA6;  OVERFLOW-X:hidden;background-color: black;width:848px;height: 800px;" id='grains_data'>None</textarea>

                </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script src="/static/assets/js/json.js"></script>

<script>
    function GetGrainsPillar(id,action) {
        $('#grains').addClass('in').css('display','block');
        $.getJSON("{% url 'SaltMinionGrains' %}",{minion:id,action:action},function (result) {
            data=JSON.stringify(result);
            var grainsvar = document.getElementById('grains_data');
            grainsvar.value= formatJson(data,true);
        })
    }

</script>




{% endblock%}

templates/saltadmin/saltjob_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
         <div class="col-sm-12">
            <p><b>Job 执行结果详细信息:</b></p>

		 </div>
        <div class="col-md-12">
            <div class="card-box" id="result" style="OVERFLOW-Y: auto; OVERFLOW-X:hidden;background-color: #1c1c1c;height: 600px">

            </div>
        </div>
    </div>
</div>


{% endblock %}