SimpletourDevops/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from webapp.views import index
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^web/', include('webapp.urls')),
    url(r'^docker/',include('dockermanager.urls')),
    url(r'^server/',include('servermanager.urls')),
   # url(r'^domain/', include('domainmanager.urls')),
    url(r'^salt/',include('saltadmin.urls')),
]

dockermanager/urls.py
from django.conf.urls import url

from dockermanager.views import (Dockercontainerlist,DockerHosts,DockerImages,DockercontainerSearch,
                                 DockerHostAdd,DockerHostDel,DockerHostEdit,DockerContainerDel,
                                 DockerContainerStop,DockerContainerStart,DockerContainerRestart,
                                 DockerImageDelete,DockerLogOutput,StartCeleryStatus,StopCeleryStatus,
                                 RestartCeleryStatus,DeleteCeleryStatus,webSocket,getsocket)

urlpatterns = [
    url(r'container/list/(\d+)$', Dockercontainerlist, name='Dockercontainerlist'),
    url(r'container/search/(?P<page>\d+)$',DockercontainerSearch,name='DockercontainerSearch'),
    url(r'container/restart/(\w+)$',DockerContainerRestart,name='DockerContainerRestart'),
    url(r'container/stop/(\w+)$', DockerContainerStop,name='DockerContainerStop'),
    url(r'container/start/(\w+)$', DockerContainerStart, name='DockerContainerStart'),
    url(r'container/logs/(\w+)$',DockerLogOutput,name='DockerLogOutput'),
    url(r'container/delete/(\w+)$',DockerContainerDel,name='DockerContainerDel'),
    url(r'container/start/task/(\w+\-\w+\-\w+\-\w+\-\w+)$',StartCeleryStatus,name='StartCeleryStatus'),
    url(r'container/restart/task/(\w+\-\w+\-\w+\-\w+\-\w+)$',RestartCeleryStatus,name='RestartCeleryStatus'),
    url(r'container/stop/task/(\w+\-\w+\-\w+\-\w+\-\w+)$',StopCeleryStatus,name='StopCeleryStatus'),
    url(r'container/delete/task/(\w+\-\w+\-\w+\-\w+\-\w+)$',DeleteCeleryStatus,name='DeleteCeleryStatus'),
    url(r'server/list/$', DockerHosts, name='DockerHosts'),
    url(r'images/list/(\d+)$',DockerImages, name='DockerImages'),
    url(r'images/del/(\d+)$', DockerImageDelete, name='DockerImageDelete'),
    url(r'server/add/$', DockerHostAdd, name='DockerHostAdd'),
    url(r'server/del/(\d+)$',DockerHostDel,name='DockerHostDel'),
    url(r'server/edit/(\d+)$',DockerHostEdit,name='DockerHostEdit'),
    url(r'webSocket/(\w+)$',webSocket,name='webSocket'),
    url(r'getSocket/(\w+)$',getsocket,name='getsocket'),
]

webapp/urls.py
from django.conf.urls import url
from webapp.views import (Login,
                          Logout,
                          Register,
                          Activate,
                          SendResetEmail,
                          ResetPassword,
                          SysrestUserpassword,
                          Userinfo)

urlpatterns = [
    url(r'login/$', Login, name='Login'),
    url(r'register/$', Register, name='Register'),
    url(r'logout/$', Logout, name='Logout'),
    url(r'activate/(?P<token>\w+@\w+.\w+.[-_\w]*\w+.[-_\w]*\w+)/$', Activate, name='Activate'),
    url(r'reset/$',SendResetEmail,name='SendResetEmail'),
    url(r'resetpass/(?P<token>\w+@\w+.\w+.[-_\w]*\w+.[-_\w]*\w+)/$', ResetPassword, name='ResetPassword'),
    url(r'userinfo/$',Userinfo, name='Userinfo'),
    url(r'restuserpass/(\d+)$', SysrestUserpassword, name='SysrestUserpassword'),

]

dockermanager/forms.py
#!/usr/bin/env python
#coding:utf-8

__author__ = 'Luodi'

from django import forms
from servermanager.models import Server
from dockermanager.models import DockerHost
from django.forms import ModelForm









class DockerServerAdd(forms.Form):
    DockerServer=forms.ModelChoiceField(required=True,
                                        error_messages={'required': u'选择主机'},
                                        queryset=Server.objects.all(),widget=forms.Select(attrs={'class':'form-control'}))

    ServerStatus = forms.ChoiceField(choices=[(0,u'禁用'),(1,u'启用')],widget=forms.Select(attrs={'class':'form-control'}))

    dockerip = forms.GenericIPAddressField(required=True,
                                           error_messages={'required': u'请输入dockerhost ip', 'invalid':u'ip地址错误'},
                                           widget=forms.TextInput(attrs={'class': 'form-control','placeholder': '宿主机IP',
                                                               }),)
    dockerport = forms.IntegerField(required=True,
                                    error_messages={'required': u'请输入dockerhost port', 'invalid':u'port输入错误'},
                                    widget=forms.TextInput(attrs={'class': 'form-control','placeholder': '宿主机端口',
                                    }),)

class DockerServerEdit(ModelForm):
    class Meta:
        model = DockerHost
        fields = ('host', 'hostip','port','enabled')

dockermanager/views.py
#coding:utf8
from django.shortcuts import render,render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from django.http import StreamingHttpResponse
from dwebsocket import accept_websocket,require_websocket
import threading
from django.http import HttpResponse
from django.db.models import Q

from django.contrib.auth.decorators import login_required
from dockermanager.models import DockerHost,Dockerimage,DockerContainer
from django.contrib.auth.decorators import permission_required

# Create your views here.
from webapp.Extends import PageList
from servermanager.models import Server
from dockermanager import forms
from Publicapi.dockerapi.Manager import Dockerapi
from webapp.tasks import StopContainer,StartContainer,RestartContainer,DeleteContainer
import  json
import docker
from webapp.models import *

@login_required()
@permission_required('dockermanger.docker_index_view',raise_exception=True)
def Dockercontainerlist(request,page):
    usersession=request.session.get('user_id')
    if request.method == 'POST':
        searchdata = request.POST.get('search')
        #分页代码
        (page,start,end,per_item)=PageList.PageCount(page)
        count = DockerContainer.objects.filter(Q(containerID__contains=searchdata) | Q(Name__contains=searchdata)).count()
        result = DockerContainer.objects.filter(Q(containerID__contains=searchdata) | Q(Name__contains=searchdata)).order_by('-id')[start:end]
        url = "/docker/container/list"
        if count%per_item == 0:
            all_pages_count = count/per_item
        else:
            all_pages_count = count/per_item+1
        page=PageList.Page(page, url, all_pages_count)

        ret = {'Containerdata': result,
               'count': count,
               'page': page,
               'usersession':usersession}
        return render(request,'dockermanager/containers_list.html',ret)

    else:

        DockerHostData= DockerHost.objects.all()
        #分页代码
        (page,start,end,per_item)=PageList.PageCount(page)
        count = DockerContainer.objects.all().count()
        result = DockerContainer.objects.all().order_by('-id')[start:end]
        url = "/docker/container/list"
        if count%per_item == 0:
            all_pages_count = count/per_item
        else:
            all_pages_count = count/per_item+1
        page=PageList.Page(page, url, all_pages_count)

        ret = {'Containerdata': result,
               'count': count,
               'DockerHostData':DockerHostData,
               'page': page,
               'usersession':usersession}
        return render(request,'dockermanager/containers_list.html',ret)


@login_required()
def DockercontainerSearch(request,page):
    usersession=request.session.get('user_id')
    if request.method == 'GET':
        searchdata = request.GET.get('search')

        ipData = request.GET.get('ipList')
        status = request.GET.get('status')

        DockerHostData = DockerHost.objects.all()
        #分页代码
        (page,start,end,per_item)=PageList.PageCount(page)


        count=DockerContainer.objects.filter(Q(hostip__contains=ipData) & Q(status__contains=status),
                                       Q(containerID__contains=searchdata) | Q(Name__contains=searchdata)).count()

        result=DockerContainer.objects.filter(Q(hostip__contains=ipData) & Q(status__contains=status),
                                                  Q(containerID__contains=searchdata) | Q(Name__contains=searchdata)).order_by('-id')[start:end]

        #count = DockerContainer.objects.filter(Q(containerID__contains=searchdata) | Q(Name__contains=searchdata)).count()
        #result = DockerContainer.objects.filter(Q(containerID__contains=searchdata) | Q(Name__contains=searchdata)).order_by('-id')[start:end]
        url = "/docker/container/search"
        print url
        search=u"?search=%s&status=%s&ipList=%s" %(searchdata,status,ipData)
        if count%per_item == 0:
            all_pages_count = count/per_item
        else:
            all_pages_count = count/per_item+1
        page=PageList.Page(page, url, all_pages_count,search)

        ret = {'Containerdata': result,
               'count': count,
               'DockerHostData': DockerHostData,
               'page': page,
               'usersession':usersession}
        return render(request,'dockermanager/containers_list.html',ret)


@login_required()
def DockerHosts(request):
    usersession=request.session.get('user_id')
    if request.method == 'POST':
        id = request.POST['id']
        status= request.POST['checkboxValue']
        if status == 'true':
            status=1
        else:
            status=0
        dockerhostdata = DockerHost.objects.get(id=id)
        dockerhostdata.enabled = status
        dockerhostdata.save()
        msg={'msginfo':u'主机状态修改成功!!!!!!'}
        return HttpResponse(json.dumps(msg))
    else:
        Hostadata=DockerHost.objects.all()
        ret={'usersession':usersession,'Hostadata':Hostadata}
        return  render(request,'dockermanager/dockerhosts_list.html',ret)


@login_required()
@permission_required('dockermanger.add_dockerhost',raise_exception=True)
def DockerHostAdd(request):

    username = request.session.get('user_name')
    restdata = {'data':'','regerror':'','usersession': request.session.get('user_id')}
    registerobj=forms.DockerServerAdd()
    restdata['data'] = registerobj

    listdata=[]
    [listdata.append(int(i.host.id)) for i in DockerHost.objects.all()]
    ServerData=Server.objects.exclude(id__in=listdata)
    restdata['ServerData']=ServerData

    if request.method == 'POST':
        form = forms.DockerServerAdd(request.POST)
        if form.is_valid():
            ServerData = request.POST['DockerServer']
            ServerData = Server.objects.get(id=ServerData)
            dockerip = request.POST['dockerip']
            dockerport = request.POST['dockerport']
            ServerStatus = int(request.POST['ServerStatus'])

            NewDockerHost=DockerHost(host=ServerData,hostip=dockerip,port=dockerport,enabled=ServerStatus)
            NewDockerHost.save()
            Operation.objects.create(Opuser=username,Opaction=u'添加Docker宿主机')
            return HttpResponseRedirect('/docker/server/list/')
        else:
            restdata['data'] = form
    return render(request,'dockermanager/dockerhosts_add.html', restdata)


@login_required()
def DockerImages(request,page):
    usersession=request.session.get('user_id')
    if request.method == 'POST':
        pass
    else:
         #分页代码
        (page,start,end,per_item)=PageList.PageCount(page)
        count = Dockerimage.objects.all().count()
        result = Dockerimage.objects.all().order_by('-id')[start:end]
        url = "/docker/images/list"
        if count%per_item == 0:
            all_pages_count = count/per_item
        else:
            all_pages_count = count/per_item+1
        page=PageList.Page(page, url, all_pages_count)

        ret = {'Imagedata': result,
               'count': count,
               'page': page,
               'usersession':usersession}
        return render(request,'dockermanager/images_list.html',ret)

@login_required()
@permission_required('dockermanger.delete_dockerimage',raise_exception=True)
def DockerImageDelete(request, imageid):
    username = request.session.get('user_name')
    if request.method == 'GET':
        Image=Dockerimage.objects.get(id=imageid)
        if Image:
            repo=Image.repository
            #查询DOCKER主机IP及端口
            ip = Image.imagehost
            port = DockerHost.objects.get(hostip=ip).port
            dockerapi = Dockerapi(ip,port)
            a=dockerapi.DeleteImages(repo)
            Image.delete()
            Operation.objects.create(Opuser=username,Opaction=u'删除Docker镜像 %s' %repo)
            return HttpResponse(a)
        else:
            return HttpResponse(u"没有该镜像!!")

@login_required()
@permission_required('dockermanger.delete_dockerhost',raise_exception=True)
def DockerHostDel(request,hostid):
    username = request.session.get('user_name')
    if request.method == 'GET':
       DockerHost.objects.get(id=hostid).delete()
       Operation.objects.create(Opuser=username,Opaction=u'删除Docker宿主机%s' %hostid)
       msg={'msginfo':u'DockerHost 删除成功!!!'}
       return HttpResponse(json.dumps(msg))

@login_required()
@permission_required('dockermanger.change_dockerhost',raise_exception=True)
def DockerHostEdit(request,hostid):
    usersession=request.session.get('user_id')
    username = request.session.get('user_name')
    HostData=DockerHost.objects.get(id=hostid)
    if request.method == 'POST':
        pass
        Operation.objects.create(Opuser=username,Opaction=u'修改Docker宿主机%s' %hostid)
    else:
        listdata=[]
        [listdata.append(int(i.host.id)) for i in DockerHost.objects.all()]
        hostid=HostData.host.id
        listdata.remove(hostid)
        ServerData=Server.objects.exclude(id__in=listdata)

        ret={'usersession':usersession,'HostData':HostData,'hostid':hostid,'ServerData':ServerData}
        return render(request,'dockermanager/dockerhosts_edit.html', ret)

@login_required()
def DockerContainerStop(request,containerid):
    username = request.session.get('user_name')
    if request.method == 'GET':
        IP=DockerContainer.objects.get(containerID=containerid).hostip
        port = DockerHost.objects.get(hostip=IP).port
        a=StopContainer.delay(dict(host=IP,port=port,container=containerid))
        Operation.objects.create(Opuser=username,Opaction=u'停止容器%s' %containerid[0:12])
        msg={'celeryId':a.id}
        return HttpResponse(json.dumps(msg))

@login_required()
def DockerContainerRestart(request,containerId):
    username = request.session.get('user_name')
    if request.method == 'GET':
        IP=DockerContainer.objects.get(containerID=containerId).hostip
        port = DockerHost.objects.get(hostip=IP).port
        a=RestartContainer.apply_async((IP, port, containerId))

templates/dockermanager/dockerhosts_add.html
{% extends 'base.html' %}

{% block content %}

    <!-- Plugins css-->


    <link href="/static/assets/plugins/bootstrap-select/dist/css/bootstrap-select.min.css" rel="stylesheet" />


<div class="container">
        <div class="row ">
                    <div class="col-sm-12">
                        <h4 class="page-title">主机添加</h4>
                        <ol class="breadcrumb">
                            <li>
                                <a href="#">容器管理</a>
                            </li>
                            <li class="active">
                                <a href="{% url 'DockerHosts' %}">主机列表</a>
                            </li>
                        </ol>
                    </div>

            <form class="form-horizontal" role="form" method="POST" action="{% url 'DockerHostAdd' %}">
                    {% csrf_token  %}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="card-box">
                                <div class="row">
                                    <div class="col-md-12">
                                             <div class="form-group">
                                                <label class="col-md-3 control-label">主机SN关联:</label>
                                                <div class="col-md-6">

                                               <select class="selectpicker show-tick" data-style="btn-white" name="DockerServer">
                                                    {% for s in ServerData %}
                                                            <option value="{{s.id}}">{{s}}</option>
                                                    {%endfor%}
                                                </select>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-md-3 control-label" for="state-warning">docker主机IP:</label>
                                                <div class="col-md-6">
                                                     {{ data.dockerip}}
								                     {{ data.dockerip.errors}}

                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-md-3 control-label" for="state-danger">docker主机port:</label>
                                                <div class="col-md-6">
                                                    {{ data.dockerport}}
								                    {{ data.dockerport.errors}}
                                                    <!--<input type="text" id="state-danger" name="state-danger" class="form-control" placeholder="...">-->
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-sm-3 control-label">主机状态: </label>
                                                <div class="col-md-6">
                                                   {{data.ServerStatus}}
                                                </div>

                                                <!--


                                                    <select class="selectpicker show-tick" data-style="btn-white">
                                                         <option value="0" >启用</option>
                                                         <option value="1" >禁用</option>
                                                    </select>
                                                </div>-->
                                            </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                     <!-- 提交按钮 -->
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-primary">
                                    提交
                                </button>
                            </div>
                        </div>
                    </div>
            </form>
         </div>
</div>


<script src="/static/assets/plugins/bootstrap-select/dist/js/bootstrap-select.min.js" type="text/javascript"></script>

{% endblock %}

templates/dockermanager/dockerhosts_edit.html
{% extends 'base.html' %}

{% block content %}

    <!-- Plugins css-->


    <link href="/static/assets/plugins/bootstrap-select/dist/css/bootstrap-select.min.css" rel="stylesheet" />


<div class="container">
        <div class="row ">
                    <div class="col-sm-12">
                        <h4 class="page-title">主机修改</h4>
                        <ol class="breadcrumb">
                            <li>
                                <a href="#">容器管理</a>
                            </li>
                            <li class="active">
                                <a href="{% url 'DockerHosts' %}">主机列表</a>
                            </li>
                        </ol>
                    </div>

            <form class="form-horizontal" role="form" method="POST" action="{% url 'DockerHostEdit' hostid %}">
                    {% csrf_token  %}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="card-box">
                                <div class="row">
                                   <div class="col-md-12">
                                             <div class="form-group">
                                                <label class="col-md-3 control-label">主机SN关联:</label>
                                                <div class="col-md-6">
                                                   <select class="selectpicker show-tick bs-select-hidden" data-style="btn-white" name="DockerServer">
                                                       {% for i in ServerData %}
                                                            {% if HostData.host.id == i.id%}
                                                                <option value="{{i.id}}" selected>{{i}}</option>
                                                            {%else%}
                                                                <option value="{{i.id}}" >{{i}}</option>
                                                            {%endif%}
                                                       {%endfor%}
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-md-3 control-label" for="state-warning">docker主机IP:</label>
                                                <div class="col-md-6">
                                                     <input class="form-control" id="id_dockerip" name="dockerip" value="{{HostData.hostip}}" placeholder="宿主机IP" type="text">
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-md-3 control-label" for="state-danger">docker主机port:</label>
                                                <div class="col-md-6">
                                                    <input class="form-control" id="id_dockerport" name="dockerport" value="{{HostData.port}}" placeholder="宿主机端口" type="text">
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-sm-3 control-label">主机状态: </label>
                                                <div class="col-md-6">
                                                   <select class="form-control" id="id_ServerStatus" name="ServerStatus">
                                                       {% if HostData.enabled == '0' %}
                                                            <option value="0" selected>禁用</option>
                                                            <option value="1">启用</option>
                                                       {%else%}
                                                            <option value="0" >禁用</option>
                                                            <option value="1" selected>启用</option>
                                                       {%endif%}
                                                   </select>
                                                </div>


                                            </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                     <!-- 提交按钮 -->
                    <div>
                        <div class="col-sm-6">
                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-primary">
                                    修改
                                </button>
                            </div>
                        </div>
                    </div>
            </form>
         </div>
</div>
<!--
<script>
    jQuery(document).ready(function(){
               $('button[type=submit]').click(function(e) {
                    e.preventDefault();
                     $.ajax({
                        type: 'POST',
                        url: '{% url "DockerHostAdd" %}',
                        data: $('.form-horizontal').serialize(),
                        success: function(data) {
                           alert(data);
                        },
                        error: function() {},
                    });

               });
    });
</script>-->

<script src="/static/assets/plugins/bootstrap-select/dist/js/bootstrap-select.min.js" type="text/javascript"></script>

{% endblock %}

templates/dockermanager/dockerhosts_list.html
{% extends 'base.html' %}

{% block content %}
<link href="/static/assets/plugins/switchery/dist/switchery.min.css" rel="stylesheet" type="text/css">


<div class="container">

						<!-- Page-Title -->
						<div class="row">
							<div class="col-sm-12">
								<h4 class="page-title">容器管理</h4>
								<ol class="breadcrumb">
									<li>
										<a href="{% url 'DockerHosts' %}">容器管理</a>
									</li>

									<li class="active">
										主机列表
									</li>
								</ol>
							</div>
						</div>

                        <div class="row">
							<div class="col-sm-10">
								<div class="row">
										<div class="col-sm-12">
											<a  href="{% url 'DockerHostAdd' %}"><button class="btn btn-primary " type="button">添加宿主机</button></a>
										</div>
									</div>
								<br>
								<div class="card-box">

									<div class="row">
										<div class="col-sm-12">
											<h4 class="m-t-0 header-title"><b>容器主机列表</b></h4>
											<div class="p-20">
												<table class="table table-striped m-0">
													<thead>
														<tr>
															<th>#</th>
															<th>设备名</th>
															<th>主机名</th>
															<th>主机IP</th>
                                                            <th>docker端口</th>
                                                            <th>启用</th>
                                                            <td>操作</td>
														</tr>
													</thead>
													<tbody>
														{% for docker in Hostadata%}
														<tr>
															<th scope="row" data-id="{{docker.id}}">{{docker.id}}</th>
															<td>{{docker.host.Assets.host_name}}</td>
															<td>{{docker.host.hostname}}</td>
															<td>{{docker.hostip}}
                                                            </td>
                                                            <td>{{docker.port}}</td>
															<td>
																{% if docker.enabled == 1 %}
																    <input type="checkbox" name="enableCheckbox" checked  class="js-switch" data-plugin="switchery" data-color="#f05050" data-size="small"/>
																{% else %}
																	<input type="checkbox" name="enableCheckbox"  class="js-switch"  data-plugin="switchery" data-color="#f05050" data-size="small"/>
																{%endif%}
															</td>
                                                             <td>
                                                                 <a  href="{% url 'DockerHostEdit' docker.id %}" class="btn btn-xs btn-info">修改</a>
																 <button  class="btn btn-xs btn-danger" onclick="hostdelete({{docker.id}})">删除</button>
                                                             </td>
														</tr>
														{% endfor%}
													</tbody>
												</table>
											</div>

										</div>
									</div>
								</div>
							</div>
						</div>
                    </div>
<script src="/static/assets/plugins/switchery/dist/switchery.min.js"></script>

<script>
	$(document).ready(function() {
		$('.switchery').click(function(e) {
			var $this = $(this);
			var checkboxValue = this.parentElement.querySelector('input').checked;
			var id = $this.parent('td').siblings('th').attr('data-id');
			if($this.hasClass('disabled')) return;
			$this.addClass('disabled');
			$.ajax({
				method: 'POST',
                dataType: 'json',
				url: '{%url 'DockerHosts' %}',
				data: {
					'id': id,
					'checkboxValue': checkboxValue,
					'csrfmiddlewaretoken': '{{ csrf_token }}',
				},
				success: function(data) {
					var msginfo=data.msginfo;
					if(msginfo){
						$.Notification.autoHideNotify('success','top right','系统通知', msginfo);
					}
					$this.removeClass('disabled');
				},
				error: function() {
					$this.removeClass('disabled');
				}
			})
		})
	})




</script>
<script>
	function hostdelete(e){
		$.ajax({
            method: "GET",
            url:"/docker/server/del/" + e,
            dataType: 'json',
            success:function(result){
                var msginfo=result.msginfo;
                var msgerror=result.msgerror;
                if(msginfo){
                    $.Notification.autoHideNotify('success','top right','系统通知', msginfo);
                    setTimeout(function() {
                          location.href = '{% url 'DockerHosts'  %}';
                     },2500);

                }else{
                    $.Notification.autoHideNotify('error', 'top right', '系统通知',msgerror);

                }

            },
            error:function(e){
                alert(e);

            }

        });
	}


</script>
{% endblock%}

templates/dockermanager/dockerhosts_logs.html
{% extends 'base.html' %}

{% block content %}



<div class="container">

			<!-- Page-Title -->
			<div class="row">
				<div class="col-sm-12">
					<h4 class="page-title">容器管理</h4>
					<ol class="breadcrumb">
						<li>
							<a href="{% url 'DockerHosts' %}">容器管理</a>
						</li>

						<li class="active">
							容器日志
						</li>
					</ol>
				</div>
			</div>

			<div class="row">
				<div style="background-color:#000000;color:#FFFFFF;" class="col-sm-12" id="containerid" data-target="{{containerid}}">
					{% for lin in dockerlogsdata %}
							{{lin}}<br>
					{%endfor%}
				</div>
			</div>
		</div>

<script>
/*第一次读取最新通知*/
  setTimeout(function() {
             Push();
           },
        200);
      /*30轮询读取函数*/
        setInterval(function() {

            Push();

    },
        2000);

/*请求函数的ajax*/
function Push() {
	a=document.getElementById("containerid");
	var id = a.getAttribute('data-target');
    $.ajax({
        type: "POST",
        url: "/docker/container/logs/" + id,
        data:{
			csrfmiddlewaretoken:'{{ csrf_token  }}',
        },
        beforeSend: function() {},
        success: function(data) {
        	document.getElementById("containerid").innerHTML='';
			for (var i=0;i<JSON.parse(data).dockerlogsdata.length;i++){
				var HtmlText=JSON.parse(data).dockerlogsdata[i] + '<br/>'
    			document.getElementById("containerid").innerHTML+=(HtmlText);
    		}
        },
    });
}

</script>
{% endblock%}